# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
#  ðŸ¥ MediTrack - Task Runner
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
#  Run 'task --list' to see all available tasks
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

version: "3"

# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
#  Environment & Variables
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
vars:
  BUN: bun
  TURBO: "{{.BUN}} turbo"
  DATABASE_URL: "postgresql://meditrack:meditrack_dev_password@localhost:5432/meditrack"
  PSQL: "docker-compose exec -T postgres psql -U meditrack -d meditrack"

env:
  DATABASE_URL: "{{.DATABASE_URL}}"

# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
#  Task Groups
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
tasks:
  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  #  ðŸ—ï¸ Build & Check
  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  build:
    desc: "ðŸ“¦ Build all packages"
    cmds:
      - "{{.TURBO}} build"

  check:
    desc: "âœ… Run type checking"
    cmds:
      - "{{.TURBO}} check-types"

  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  #  ï¿½ï¸ Tauri Desktop App
  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  tauri:dev:
    desc: "ðŸ–¥ï¸  Start Tauri desktop app in dev mode"
    dir: apps/web
    cmds:
      - "{{.BUN}} tauri dev"

  tauri:build:
    desc: "ðŸ“¦ Build Tauri desktop app"
    dir: apps/web
    cmds:
      - "{{.BUN}} tauri build"

  tauri:build:debug:
    desc: "ðŸ› Build Tauri app with debug symbols"
    dir: apps/web
    cmds:
      - "{{.BUN}} tauri build --debug"

  tauri:icon:
    desc: "ðŸŽ¨ Generate app icons from source"
    dir: apps/web
    cmds:
      - "{{.BUN}} tauri icon"

  tauri:info:
    desc: "â„¹ï¸  Show Tauri environment info"
    dir: apps/web
    cmds:
      - "{{.BUN}} tauri info"

  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  #  ï¿½ Docker Services
  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  docker:up:
    desc: "ðŸš€ Start all Docker services"
    cmds:
      - docker-compose up -d

  docker:build:
    desc: "ðŸ”¨ Build custom PostgreSQL image with extensions"
    cmds:
      - docker-compose build postgres
      - echo "âœ… Custom PostgreSQL image built with pgvector and pg_textsearch"

  docker:down:
    desc: "ðŸ›‘ Stop all Docker services"
    cmds:
      - docker-compose down

  docker:restart:
    desc: "ðŸ”„ Restart all Docker services"
    cmds:
      - docker-compose restart

  docker:logs:
    desc: "ðŸ“‹ View Docker service logs"
    cmds:
      - docker-compose logs -f

  docker:ps:
    desc: "ðŸ“Š Show Docker service status"
    cmds:
      - docker-compose ps

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  #  PostgreSQL Database
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  docker:db:start:
    desc: "ðŸš€ Start PostgreSQL database"
    cmds:
      - docker-compose up -d postgres
      - echo "â³ Waiting for database to be ready..."
      - sleep 5
      - docker-compose exec postgres pg_isready -U meditrack -d meditrack || echo "âš ï¸  Database not ready yet, please wait..."

  docker:db:stop:
    desc: "ðŸ›‘ Stop PostgreSQL database"
    cmds:
      - docker-compose stop postgres

  docker:db:restart:
    desc: "ðŸ”„ Restart PostgreSQL database"
    cmds:
      - docker-compose restart postgres

  docker:db:logs:
    desc: "ðŸ“‹ View PostgreSQL logs"
    cmds:
      - docker-compose logs -f postgres

  docker:db:shell:
    desc: "ðŸš Open PostgreSQL shell"
    cmds:
      - docker-compose exec postgres psql -U meditrack -d meditrack

  docker:db:reset:
    desc: "ðŸ—‘ï¸  Reset database (DESTRUCTIVE)"
    cmds:
      - cmd: docker-compose down -v
        prompt: "âš ï¸  This will DELETE ALL DATA. Continue?"
      - docker-compose up -d postgres
      - echo "â³ Waiting for database to be ready..."
      - sleep 5

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  #  pgAdmin
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  docker:pgadmin:start:
    desc: "ðŸŽ¨ Start pgAdmin (http://localhost:5050)"
    cmds:
      - docker-compose --profile admin up -d
      - echo "âœ… pgAdmin started at http://localhost:5050"
      - echo "Email admin@meditrack.local"
      - echo "Password admin"

  docker:pgadmin:stop:
    desc: "ðŸ›‘ Stop pgAdmin"
    cmds:
      - docker-compose stop pgadmin

  docker:pgadmin:logs:
    desc: "ðŸ“‹ View pgAdmin logs"
    cmds:
      - docker-compose logs -f pgadmin

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  #  Drizzle Studio
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  db:studio:
    desc: "ðŸŽ¨ Open Drizzle Studio (https://local.drizzle.studio)"
    cmds:
      - echo "ðŸš€ Starting Drizzle Studio..."
      - echo "ðŸ“ URL https://local.drizzle.studio"
      - echo "âš ï¸  Press Ctrl+C to stop"
      - "{{.BUN}} run db:studio"

  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  #  Redis Cache
  # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  docker:redis:start:
    desc: "ðŸš€ Start Redis cache"
    cmds:
      - docker-compose --profile cache up -d redis

  docker:redis:stop:
    desc: "ðŸ›‘ Stop Redis cache"
    cmds:
      - docker-compose stop redis

  docker:redis:cli:
    desc: "ðŸ”§ Open Redis CLI"
    cmds:
      - docker-compose exec redis redis-cli -a meditrack_redis_password

  docker:redis:logs:
    desc: "ðŸ“‹ View Redis logs"
    cmds:
      - docker-compose logs -f redis

  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  #  ðŸ—„ï¸ Database Management
  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  db:setup:
    desc: "ðŸŽ¯ Complete database setup (Docker + migrations)"
    cmds:
      - task: docker:db:start
      - echo "â³ Waiting for database to be fully ready..."
      - sleep 3
      - task: db:check
      - task: db:build
      - task: db:migrate

  db:dev:setup:
    desc: "ðŸ› ï¸  Setup database for development (fresh install)"
    cmds:
      - task: docker:db:reset
      - echo "â³ Waiting for database to be fully ready..."
      - sleep 3
      - task: db:check
      - task: db:build
      - task: db:migrate:fresh

  db:migrate:
    desc: "ðŸš€ Run all pending database migrations"
    dir: apps/web/src-tauri/db/migration
    cmds:
      - cargo run -- up

  db:migrate:status:
    desc: "ðŸ“Š Check database migration status"
    dir: apps/web/src-tauri/db/migration
    cmds:
      - cargo run -- status

  db:migrate:rollback:
    desc: "âª Rollback last database migration"
    dir: apps/web/src-tauri/db/migration
    cmds:
      - cargo run -- down

  db:migrate:fresh:
    desc: "ðŸ”„ Drop all tables and rerun migrations (DESTRUCTIVE)"
    dir: apps/web/src-tauri/db/migration
    cmds:
      - cmd: cargo run -- fresh
        prompt: "âš ï¸  This will DROP ALL TABLES and data. Continue?"

  db:migrate:refresh:
    desc: "ðŸ”„ Rollback all migrations and reapply (DESTRUCTIVE)"
    dir: apps/web/src-tauri/db/migration
    cmds:
      - cmd: cargo run -- refresh
        prompt: "âš ï¸  This will rollback and reapply all migrations. Continue?"

  db:migrate:reset:
    desc: "ðŸ—‘ï¸  Rollback all migrations (DESTRUCTIVE)"
    dir: apps/web/src-tauri/db/migration
    cmds:
      - cmd: cargo run -- reset
        prompt: "âš ï¸  This will rollback all migrations. Continue?"

  db:check:
    desc: "âœ… Check database migration code compiles"
    dir: apps/web/src-tauri/db/migration
    cmds:
      - cargo check --all-targets

  db:build:
    desc: "ðŸ”¨ Build database migration binary"
    dir: apps/web/src-tauri/db/migration
    cmds:
      - cargo build --bin migration

  db:build:release:
    desc: "ðŸ“¦ Build database migration binary (release)"
    dir: apps/web/src-tauri/db/migration
    cmds:
      - cargo build --bin migration --release

  db:verify:
    desc: "ðŸ” Verify database schema"
    cmds:
      - "{{.PSQL}} -c \"\\dt\""
      - "{{.PSQL}} -c \"\\dT\""
      - "{{.PSQL}} -c \"\\di\""

  db:roles:
    desc: "ðŸ‘¥ List default roles in database"
    cmds:
      - "{{.PSQL}} -c \"SELECT name, display_name, level, is_system FROM roles ORDER BY level DESC;\""

  db:connect:
    desc: "ðŸ”Œ Connect to database with psql"
    cmds:
      - docker-compose exec postgres psql -U meditrack -d meditrack

  db:setup:
    desc: "ðŸŽ¯ Complete database setup (check, build, migrate)"
    cmds:
      - task: db:check
      - task: db:build
      - task: db:migrate

  db:dev:setup:
    desc: "ðŸ› ï¸  Setup database for development (fresh install)"
    cmds:
      - task: db:check
      - task: db:build
      - task: db:migrate:fresh

  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  #  ðŸ§ª Database Testing & Validation
  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  db:test:connection:
    desc: "ðŸ”Œ Test database connection"
    cmds:
      - "{{.PSQL}} -c \"SELECT version();\""

  db:test:enums:
    desc: "ðŸ·ï¸  Test ENUM types exist"
    cmds:
      - "{{.PSQL}} -c \"SELECT typname FROM pg_type WHERE typtype = 'e' ORDER BY typname;\""

  db:test:tables:
    desc: "ðŸ“‹ Test tables exist"
    cmds:
      - "{{.PSQL}} -c \"SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename;\""

  db:test:indexes:
    desc: "ðŸ“‡ Test indexes exist"
    cmds:
      - "{{.PSQL}} -c \"SELECT indexname FROM pg_indexes WHERE schemaname = 'public' ORDER BY indexname;\""

  db:test:triggers:
    desc: "âš¡ Test triggers exist"
    cmds:
      - "{{.PSQL}} -c \"SELECT trigger_name, event_object_table FROM information_schema.triggers WHERE trigger_schema = 'public' ORDER BY trigger_name;\""

  db:test:foreign-keys:
    desc: "ðŸ”— Test foreign keys exist"
    cmds:
      - "{{.PSQL}} -c \"SELECT conname, conrelid::regclass, confrelid::regclass FROM pg_constraint WHERE contype = 'f' ORDER BY conname;\""

  db:test:all:
    desc: "ðŸ§ª Run all database tests"
    cmds:
      - echo "Testing database connection..."
      - task: db:test:connection
      - echo "\nTesting ENUM types..."
      - task: db:test:enums
      - echo "\nTesting tables..."
      - task: db:test:tables
      - echo "\nTesting indexes..."
      - task: db:test:indexes
      - echo "\nTesting triggers..."
      - task: db:test:triggers
      - echo "\nTesting foreign keys..."
      - task: db:test:foreign-keys
      - echo "\nâœ… All database tests completed!"

  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  #  ðŸ“Š Database Information & Stats
  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  db:info:
    desc: "â„¹ï¸  Show database information"
    cmds:
      - echo "=== Database Information ==="
      - "{{.PSQL}} -c \"SELECT current_database(), current_user, version();\""

  db:size:
    desc: "ðŸ“ Show database size"
    cmds:
      - "{{.PSQL}} -c \"SELECT pg_size_pretty(pg_database_size(current_database())) as size;\""

  db:tables:size:
    desc: "ðŸ“Š Show table sizes"
    cmds:
      - "{{.PSQL}} -c \"SELECT schemaname, tablename, pg_size_pretty(pg_total_relation_size(schemaname||'.'||tablename)) AS size FROM pg_tables WHERE schemaname = 'public' ORDER BY pg_total_relation_size(schemaname||'.'||tablename) DESC;\""

  db:stats:
    desc: "ðŸ“ˆ Show database statistics"
    cmds:
      - echo "=== Table Row Counts ==="
      - "{{.PSQL}} -c \"SELECT schemaname, tablename, n_live_tup as rows FROM pg_stat_user_tables WHERE schemaname = 'public' ORDER BY n_live_tup DESC;\""
      - echo "\n=== Index Usage ==="
      - "{{.PSQL}} -c \"SELECT schemaname, tablename, indexname, idx_scan as scans FROM pg_stat_user_indexes WHERE schemaname = 'public' ORDER BY idx_scan DESC LIMIT 10;\""

  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  #  ðŸ”§ Database Maintenance
  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  db:vacuum:
    desc: "ðŸ§¹ Vacuum database (cleanup)"
    cmds:
      - "{{.PSQL}} -c \"VACUUM ANALYZE;\""

  db:backup:
    desc: "ðŸ’¾ Backup database to file"
    cmds:
      - docker-compose exec -T postgres pg_dump -U meditrack meditrack > backup_$(date +%Y%m%d_%H%M%S).sql
      - echo "âœ… Backup created"

  db:restore:
    desc: "ðŸ“¥ Restore database from backup file"
    vars:
      BACKUP_FILE: '{{.BACKUP_FILE | default "backup.sql"}}'
    cmds:
      - cmd: docker-compose exec -T postgres psql -U meditrack -d meditrack < {{.BACKUP_FILE}}
        prompt: "âš ï¸  This will restore from {{.BACKUP_FILE}}. Continue?"

  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  #  ðŸ§¹ Database Cleanup
  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  db:clean:soft-deleted:
    desc: "ðŸ—‘ï¸  Permanently delete soft-deleted records (DESTRUCTIVE)"
    cmds:
      - cmd: |
          {{.PSQL}} -c "DELETE FROM users WHERE deleted_at IS NOT NULL;"
          {{.PSQL}} -c "DELETE FROM staff WHERE deleted_at IS NOT NULL;"
          {{.PSQL}} -c "DELETE FROM roles WHERE deleted_at IS NOT NULL;"
          echo "âœ… Soft-deleted records permanently removed"
        prompt: "âš ï¸  This will permanently delete all soft-deleted records. Continue?"

  db:clean:test-data:
    desc: "ðŸ§¹ Remove test/sample data (DESTRUCTIVE)"
    cmds:
      - cmd: |
          {{.PSQL}} -c "DELETE FROM users WHERE username LIKE 'test%' OR email LIKE 'test%';"
          {{.PSQL}} -c "DELETE FROM staff WHERE employee_id LIKE 'TEST%' OR email LIKE 'test%';"
          echo "âœ… Test data removed"
        prompt: "âš ï¸  This will delete all test data. Continue?"

  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  #  ðŸŒ± Database Seeding
  # â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  seed:
    desc: "ðŸŒ± Run database seeder (interactive TUI)"
    dir: apps/web/src-tauri/crates/seeder
    cmds:
      - cargo run

  seed:check:
    desc: "âœ… Check seeder code compiles"
    dir: apps/web/src-tauri/crates/seeder
    cmds:
      - cargo check --all-targets

  seed:build:
    desc: "ðŸ”¨ Build seeder binary"
    dir: apps/web/src-tauri/crates/seeder
    cmds:
      - cargo build --bin app_seeder

  seed:build:release:
    desc: "ðŸ“¦ Build seeder binary (release)"
    dir: apps/web/src-tauri/crates/seeder
    cmds:
      - cargo build --bin app_seeder --release

  seed:run:
    desc: "ðŸš€ Run seeder in release mode"
    dir: apps/web/src-tauri/crates/seeder
    cmds:
      - cargo run --release

  seed:watch:
    desc: "ðŸ‘€ Watch and rebuild seeder on changes"
    dir: apps/web/src-tauri/crates/seeder
    cmds:
      - cargo watch -x run
