/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SpecialOrdersRouteImport } from './routes/special-orders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'

const OnboardingIndexLazyRouteImport = createFileRoute('/onboarding/')()
const InventoryStockAdjustmentsIndexLazyRouteImport = createFileRoute(
  '/inventory/stock-adjustments/',
)()
const InventoryMedicineFormsIndexLazyRouteImport = createFileRoute(
  '/inventory/medicine-forms/',
)()
const InventoryManufacturersIndexLazyRouteImport = createFileRoute(
  '/inventory/manufacturers/',
)()
const InventoryItemsIndexLazyRouteImport =
  createFileRoute('/inventory/items/')()
const InventoryItemInquiryIndexLazyRouteImport = createFileRoute(
  '/inventory/item-inquiry/',
)()

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialOrdersRoute = SpecialOrdersRouteImport.update({
  id: '/special-orders',
  path: '/special-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexLazyRoute = OnboardingIndexLazyRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/onboarding/index.lazy').then((d) => d.Route),
)
const InventoryStockAdjustmentsIndexLazyRoute =
  InventoryStockAdjustmentsIndexLazyRouteImport.update({
    id: '/inventory/stock-adjustments/',
    path: '/inventory/stock-adjustments/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/inventory/stock-adjustments/index.lazy').then(
      (d) => d.Route,
    ),
  )
const InventoryMedicineFormsIndexLazyRoute =
  InventoryMedicineFormsIndexLazyRouteImport.update({
    id: '/inventory/medicine-forms/',
    path: '/inventory/medicine-forms/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/inventory/medicine-forms/index.lazy').then((d) => d.Route),
  )
const InventoryManufacturersIndexLazyRoute =
  InventoryManufacturersIndexLazyRouteImport.update({
    id: '/inventory/manufacturers/',
    path: '/inventory/manufacturers/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/inventory/manufacturers/index.lazy').then((d) => d.Route),
  )
const InventoryItemsIndexLazyRoute = InventoryItemsIndexLazyRouteImport.update({
  id: '/inventory/items/',
  path: '/inventory/items/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/inventory/items/index.lazy').then((d) => d.Route),
)
const InventoryItemInquiryIndexLazyRoute =
  InventoryItemInquiryIndexLazyRouteImport.update({
    id: '/inventory/item-inquiry/',
    path: '/inventory/item-inquiry/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/inventory/item-inquiry/index.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/special-orders': typeof SpecialOrdersRoute
  '/suppliers': typeof SuppliersRoute
  '/onboarding/': typeof OnboardingIndexLazyRoute
  '/inventory/item-inquiry/': typeof InventoryItemInquiryIndexLazyRoute
  '/inventory/items/': typeof InventoryItemsIndexLazyRoute
  '/inventory/manufacturers/': typeof InventoryManufacturersIndexLazyRoute
  '/inventory/medicine-forms/': typeof InventoryMedicineFormsIndexLazyRoute
  '/inventory/stock-adjustments/': typeof InventoryStockAdjustmentsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/special-orders': typeof SpecialOrdersRoute
  '/suppliers': typeof SuppliersRoute
  '/onboarding': typeof OnboardingIndexLazyRoute
  '/inventory/item-inquiry': typeof InventoryItemInquiryIndexLazyRoute
  '/inventory/items': typeof InventoryItemsIndexLazyRoute
  '/inventory/manufacturers': typeof InventoryManufacturersIndexLazyRoute
  '/inventory/medicine-forms': typeof InventoryMedicineFormsIndexLazyRoute
  '/inventory/stock-adjustments': typeof InventoryStockAdjustmentsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/special-orders': typeof SpecialOrdersRoute
  '/suppliers': typeof SuppliersRoute
  '/onboarding/': typeof OnboardingIndexLazyRoute
  '/inventory/item-inquiry/': typeof InventoryItemInquiryIndexLazyRoute
  '/inventory/items/': typeof InventoryItemsIndexLazyRoute
  '/inventory/manufacturers/': typeof InventoryManufacturersIndexLazyRoute
  '/inventory/medicine-forms/': typeof InventoryMedicineFormsIndexLazyRoute
  '/inventory/stock-adjustments/': typeof InventoryStockAdjustmentsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/login'
    | '/reports'
    | '/settings'
    | '/special-orders'
    | '/suppliers'
    | '/onboarding/'
    | '/inventory/item-inquiry/'
    | '/inventory/items/'
    | '/inventory/manufacturers/'
    | '/inventory/medicine-forms/'
    | '/inventory/stock-adjustments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/login'
    | '/reports'
    | '/settings'
    | '/special-orders'
    | '/suppliers'
    | '/onboarding'
    | '/inventory/item-inquiry'
    | '/inventory/items'
    | '/inventory/manufacturers'
    | '/inventory/medicine-forms'
    | '/inventory/stock-adjustments'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/login'
    | '/reports'
    | '/settings'
    | '/special-orders'
    | '/suppliers'
    | '/onboarding/'
    | '/inventory/item-inquiry/'
    | '/inventory/items/'
    | '/inventory/manufacturers/'
    | '/inventory/medicine-forms/'
    | '/inventory/stock-adjustments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SpecialOrdersRoute: typeof SpecialOrdersRoute
  SuppliersRoute: typeof SuppliersRoute
  OnboardingIndexLazyRoute: typeof OnboardingIndexLazyRoute
  InventoryItemInquiryIndexLazyRoute: typeof InventoryItemInquiryIndexLazyRoute
  InventoryItemsIndexLazyRoute: typeof InventoryItemsIndexLazyRoute
  InventoryManufacturersIndexLazyRoute: typeof InventoryManufacturersIndexLazyRoute
  InventoryMedicineFormsIndexLazyRoute: typeof InventoryMedicineFormsIndexLazyRoute
  InventoryStockAdjustmentsIndexLazyRoute: typeof InventoryStockAdjustmentsIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-orders': {
      id: '/special-orders'
      path: '/special-orders'
      fullPath: '/special-orders'
      preLoaderRoute: typeof SpecialOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/stock-adjustments/': {
      id: '/inventory/stock-adjustments/'
      path: '/inventory/stock-adjustments'
      fullPath: '/inventory/stock-adjustments/'
      preLoaderRoute: typeof InventoryStockAdjustmentsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/medicine-forms/': {
      id: '/inventory/medicine-forms/'
      path: '/inventory/medicine-forms'
      fullPath: '/inventory/medicine-forms/'
      preLoaderRoute: typeof InventoryMedicineFormsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/manufacturers/': {
      id: '/inventory/manufacturers/'
      path: '/inventory/manufacturers'
      fullPath: '/inventory/manufacturers/'
      preLoaderRoute: typeof InventoryManufacturersIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/items/': {
      id: '/inventory/items/'
      path: '/inventory/items'
      fullPath: '/inventory/items/'
      preLoaderRoute: typeof InventoryItemsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/item-inquiry/': {
      id: '/inventory/item-inquiry/'
      path: '/inventory/item-inquiry'
      fullPath: '/inventory/item-inquiry/'
      preLoaderRoute: typeof InventoryItemInquiryIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SpecialOrdersRoute: SpecialOrdersRoute,
  SuppliersRoute: SuppliersRoute,
  OnboardingIndexLazyRoute: OnboardingIndexLazyRoute,
  InventoryItemInquiryIndexLazyRoute: InventoryItemInquiryIndexLazyRoute,
  InventoryItemsIndexLazyRoute: InventoryItemsIndexLazyRoute,
  InventoryManufacturersIndexLazyRoute: InventoryManufacturersIndexLazyRoute,
  InventoryMedicineFormsIndexLazyRoute: InventoryMedicineFormsIndexLazyRoute,
  InventoryStockAdjustmentsIndexLazyRoute:
    InventoryStockAdjustmentsIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
