/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SpecialOrdersRouteImport } from './routes/special-orders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialOrdersRoute = SpecialOrdersRouteImport.update({
  id: '/special-orders',
  path: '/special-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/special-orders': typeof SpecialOrdersRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/special-orders': typeof SpecialOrdersRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/special-orders': typeof SpecialOrdersRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/reports'
    | '/settings'
    | '/special-orders'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/404' | '/reports' | '/settings' | '/special-orders' | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/reports'
    | '/settings'
    | '/special-orders'
    | '/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SpecialOrdersRoute: typeof SpecialOrdersRoute
  SuppliersRoute: typeof SuppliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-orders': {
      id: '/special-orders'
      path: '/special-orders'
      fullPath: '/special-orders'
      preLoaderRoute: typeof SpecialOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SpecialOrdersRoute: SpecialOrdersRoute,
  SuppliersRoute: SuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
