#!/usr/bin/env bun

import { writeFile } from "fs/promises";
import { join } from "path";

async function generateTypes() {
  const typeDefinition = `// Auto-generated type definitions for i18next
// Do not edit this file manually

import "i18next";

// Import translation files
import type common from "../locales/en/common.json";
import type orders from "../locales/en/orders.json";
import type suppliers from "../locales/en/suppliers.json";
import type settings from "../locales/en/settings.json";
import type validation from "../locales/en/validation.json";

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: "common";
    resources: {
      common: typeof common;
      orders: typeof orders;
      suppliers: typeof suppliers;
      settings: typeof settings;
      validation: typeof validation;
    };
    returnNull: false;
  }
}
`;

  const outputPath = join(process.cwd(), "src", "types", "i18n.d.ts");
  await writeFile(outputPath, typeDefinition, "utf-8");

  console.log("✅ Type definitions generated successfully at:", outputPath);
}

generateTypes().catch((error) => {
  console.error("❌ Failed to generate types:", error);
  process.exit(1);
});
