// Auto-generated type definitions for i18next
// Do not edit this file manually

import "i18next";

// Import translation files
import type common from "../locales/en/common.json";
import type orders from "../locales/en/orders.json";
import type suppliers from "../locales/en/suppliers.json";
import type settings from "../locales/en/settings.json";
import type validation from "../locales/en/validation.json";

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: "common";
    resources: {
      common: typeof common;
      orders: typeof orders;
      suppliers: typeof suppliers;
      settings: typeof settings;
      validation: typeof validation;
    };
    returnNull: false;
  }
}
